/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RubricRouteImport } from './routes/rubric'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GradingRouteImport } from './routes/grading'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AssignmentsIndexRouteImport } from './routes/assignments.index'
import { Route as StudentStudentIdRouteImport } from './routes/student.$studentId'
import { Route as GraphAssignmentIdRouteImport } from './routes/graph.$assignmentId'
import { Route as AssignmentsAssignmentIdRouteImport } from './routes/assignments.$assignmentId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RubricRoute = RubricRouteImport.update({
  id: '/rubric',
  path: '/rubric',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GradingRoute = GradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AssignmentsIndexRoute = AssignmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssignmentsRoute,
} as any)
const StudentStudentIdRoute = StudentStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentRoute,
} as any)
const GraphAssignmentIdRoute = GraphAssignmentIdRouteImport.update({
  id: '/graph/$assignmentId',
  path: '/graph/$assignmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsAssignmentIdRoute = AssignmentsAssignmentIdRouteImport.update({
  id: '/$assignmentId',
  path: '/$assignmentId',
  getParentRoute: () => AssignmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/rubric': typeof RubricRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRouteWithChildren
  '/upload': typeof UploadRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/graph/$assignmentId': typeof GraphAssignmentIdRoute
  '/student/$studentId': typeof StudentStudentIdRoute
  '/assignments/': typeof AssignmentsIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/rubric': typeof RubricRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/graph/$assignmentId': typeof GraphAssignmentIdRoute
  '/student/$studentId': typeof StudentStudentIdRoute
  '/assignments': typeof AssignmentsIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/feedback': typeof FeedbackRoute
  '/grading': typeof GradingRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/review': typeof ReviewRoute
  '/rubric': typeof RubricRoute
  '/settings': typeof SettingsRoute
  '/student': typeof StudentRouteWithChildren
  '/upload': typeof UploadRoute
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/graph/$assignmentId': typeof GraphAssignmentIdRoute
  '/student/$studentId': typeof StudentStudentIdRoute
  '/assignments/': typeof AssignmentsIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assignments'
    | '/chat'
    | '/dashboard'
    | '/feedback'
    | '/grading'
    | '/login'
    | '/notifications'
    | '/register'
    | '/review'
    | '/rubric'
    | '/settings'
    | '/student'
    | '/upload'
    | '/assignments/$assignmentId'
    | '/graph/$assignmentId'
    | '/student/$studentId'
    | '/assignments/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/chat'
    | '/dashboard'
    | '/feedback'
    | '/grading'
    | '/login'
    | '/notifications'
    | '/register'
    | '/review'
    | '/rubric'
    | '/settings'
    | '/upload'
    | '/assignments/$assignmentId'
    | '/graph/$assignmentId'
    | '/student/$studentId'
    | '/assignments'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assignments'
    | '/chat'
    | '/dashboard'
    | '/feedback'
    | '/grading'
    | '/login'
    | '/notifications'
    | '/register'
    | '/review'
    | '/rubric'
    | '/settings'
    | '/student'
    | '/upload'
    | '/assignments/$assignmentId'
    | '/graph/$assignmentId'
    | '/student/$studentId'
    | '/assignments/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssignmentsRoute: typeof AssignmentsRouteWithChildren
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  FeedbackRoute: typeof FeedbackRoute
  GradingRoute: typeof GradingRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ReviewRoute: typeof ReviewRoute
  RubricRoute: typeof RubricRoute
  SettingsRoute: typeof SettingsRoute
  StudentRoute: typeof StudentRouteWithChildren
  UploadRoute: typeof UploadRoute
  GraphAssignmentIdRoute: typeof GraphAssignmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rubric': {
      id: '/rubric'
      path: '/rubric'
      fullPath: '/rubric'
      preLoaderRoute: typeof RubricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grading': {
      id: '/grading'
      path: '/grading'
      fullPath: '/grading'
      preLoaderRoute: typeof GradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/assignments/': {
      id: '/assignments/'
      path: '/'
      fullPath: '/assignments/'
      preLoaderRoute: typeof AssignmentsIndexRouteImport
      parentRoute: typeof AssignmentsRoute
    }
    '/student/$studentId': {
      id: '/student/$studentId'
      path: '/$studentId'
      fullPath: '/student/$studentId'
      preLoaderRoute: typeof StudentStudentIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/graph/$assignmentId': {
      id: '/graph/$assignmentId'
      path: '/graph/$assignmentId'
      fullPath: '/graph/$assignmentId'
      preLoaderRoute: typeof GraphAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$assignmentId': {
      id: '/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AssignmentsAssignmentIdRouteImport
      parentRoute: typeof AssignmentsRoute
    }
  }
}

interface AssignmentsRouteChildren {
  AssignmentsAssignmentIdRoute: typeof AssignmentsAssignmentIdRoute
  AssignmentsIndexRoute: typeof AssignmentsIndexRoute
}

const AssignmentsRouteChildren: AssignmentsRouteChildren = {
  AssignmentsAssignmentIdRoute: AssignmentsAssignmentIdRoute,
  AssignmentsIndexRoute: AssignmentsIndexRoute,
}

const AssignmentsRouteWithChildren = AssignmentsRoute._addFileChildren(
  AssignmentsRouteChildren,
)

interface StudentRouteChildren {
  StudentStudentIdRoute: typeof StudentStudentIdRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentIdRoute: StudentStudentIdRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssignmentsRoute: AssignmentsRouteWithChildren,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  FeedbackRoute: FeedbackRoute,
  GradingRoute: GradingRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ReviewRoute: ReviewRoute,
  RubricRoute: RubricRoute,
  SettingsRoute: SettingsRoute,
  StudentRoute: StudentRouteWithChildren,
  UploadRoute: UploadRoute,
  GraphAssignmentIdRoute: GraphAssignmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
